modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "All rights reserved"
issueTrackerURL = "https://www.github.com/MincraftEinstein/MendableAnvils/issues"

[[mods]]
    modId = "mendable_anvils"
    version = "${version}"
    displayName = "Mendable Anvils"
    #updateJSONURL = "https://change.me.example.invalid/updates.json"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/mendable-anvils"
    logoFile = "banner.png"
    authors = "MincraftEinstein"
    displayTest = "IGNORE_SERVER_VERSION"
    description = "${description}"

[modproperties.mendable_anvils]
    catalogueImageIcon = "pack.png"

[[dependencies.mendable_anvils]]
    modId = "forge"
    mandatory = true
    versionRange = "[${forge_version},)"
    ordering = "NONE"
    side = "SERVER"

[[dependencies.mendable_anvils]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "SERVER"
