modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://www.github.com/MincraftEinstein/MendableAnvils/issues"

[[mods]]
    modId="mendable_anvils"
    version="${version}"
    displayName="Mendable Anvils"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mendable-anvils-forge"
    logoFile="banner.png"
    credits=""
    authors="MincraftEinstein"
    displayTest="IGNORE_SERVER_VERSION"
    description='''
A mod that allows players to fix their anvils by shift + right-clicking an anvil with an iron ingot
'''

[modproperties.mendable_anvils]
    catalogueImageIcon="pack.png"

[[dependencies.mendable_anvils]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mendable_anvils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20, 1.21)"
    ordering="NONE"
    side="BOTH"
