modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://www.github.com/MincraftEinstein/MendableAnvils/issues" #optional

[[mods]]
    modId="mendable_anvils"
    version="${version}"
    displayName="Example Mod"
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mendable-anvils-forge"
    logoFile="assets/mendable_anvils/logo.png"
    credits=""
    authors="MincraftEinstein"
    description='''
A simple mod that allows a player to fix their anvils by shift + right-clicking an anvil with an iron ingot
'''

[[dependencies.mendable_anvils]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mendable_anvils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="BOTH"
