modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "All rights reserved"
issueTrackerURL = "https://www.github.com/MincraftEinstein/MendableAnvils/issues"

[[mods]]
    modId = "mendable_anvils"
    version = "${version}"
    displayName = "${mod_name}"
    #updateJSONURL = "https://change.me.example.invalid/updates.json"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/mendable-anvils"
    logoFile = "banner.png"
    authors = "${mod_author}"
    description = "${description}"

[modproperties.mendable_anvils]
    catalogueImageIcon = "pack.png"

[[dependencies.mendable_anvils]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge_version},)"
    ordering = "NONE"
    side = "SERVER"

[[dependencies.mendable_anvils]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "SERVER"
